### PR TITLE
For b205, the words systemverilog: ".ref" and "checker" are renamed.

### PR DESCRIPTION
**Pull request by pentin-as**

### CODE REVIEW

**Comment by michael-west** [comment]
Thank you for submitting the pull request!  The changes are under review.

**Comment by mbr0wn** [comment]
What was the motivation for this? Are `checker` and `ref` reserved in some context?

**Comment by pentin-as** [comment]
.ref and checker are systemverilog service words.
I use the b205mini card to run my IP cores. My IP cores contained synthesizable elements of the language systemverilog. However, due to the fact that this language is not supported by ISE, they had to be removed. Thus, this correction is no longer needed.
Nevertheless, it seems to me, it is better to avoid using the service words of the language systemverilog.

**Comment by achaudhari** [comment]
Thanks for submitting the pull request @pentin-as. The changes are great and they do seem to solve a lot of compiler warnings. However, we are currently treating the B2xx codebase as stable and are only pushing bugfixes for that product line. Your changes, while useful, would add too much risk so we unfortunately have to decline them. We really appreciate your effort to upstream the fixes, though.

**Pull request closed without merging**
