### PR TITLE
Work In Progress-  Possible changes for building RFNOC Out-Of-Tree modules

### PR DESCRIPTION
**Pull request by ejk43**
Hi, 

This pull request is intended to demonstrate how I'm currently including rfnoc out-of-tree modules. It starts to solves a few issues I ran into with the rfnoc build process (but is nowhere near complete).

I have **not** made the corresponding changes in rfnocmodtool, so I would not expect these changes to get integrated into mainstream rfnoc build. I just want to demonstrate my workflow and start a conversation about how to improve the build process for rfnoc OOT modules. 

The issues are:

1. **The rfnocmodtool hardcodes the generated Makefile.srcs to use the local path (e.g. "/home/ejk/prefix") which is not portable across different machines**... The change in this pull request lets OOT modules reference an "OOT_DIR" environment variable which is eventually set from the pybombs prefix when building an FPGA image. With this change, I've been able to move the same OOT module source code to different machines without any problems.  An example Makefile.srcs I use for OOT rfnoc sources is attached here: [Makefile.srcs](https://github.com/EttusResearch/fpga/files/676035/Makefile.srcs.txt)

2.  **Cannot include xilinx vivado IP generated in an OOT module.** I also edited the python make.py script to look for an IP directory in the rfnoc OOT module and then include these source files. The Makefile.inc in the IP directory is formatted similar to usrp3_rfnoc/lib/ip/Makefile.inc. An example Makefile.inc I use for my OOT ip directory is attached: [Makefile.inc](https://github.com/EttusResearch/fpga/files/676037/Makefile.inc.txt)

3. **I also had trouble running an HDL simulation using OOT sources that were not the top level noc_block_xx or noc_block_xx_tb**. From what I can tell, these OOT source files need to be included in the "VIV_DESIGN_SRCS" value in usrp3_rfnoc/tools/make/viv_simulator.mak. To that end, I added a line in Makefile.srcs that looks for files in the variable OOT_SRCS, which I populate in the Makefile for my OOT testbench.  

That's about it for now. Would look forward to feedback or code updates to resolve these issues  :) 

EJ

### CODE REVIEW

**Comment by primercuervo** [comment]
Hello @ejk43 

This is a nice set of modifications you have there! Part of this has already been discussed internally and is planned to be added as new features for rfnocmodtool and uhd_image_builder.py (former make.py). Be sure that your suggestions will be held into consideration and that an update for this tools will come soon!

Thanks!

**Comment by ejk43** [comment]
Hey @primercuervo, cool! Sounds good. 

Let me know if you can use an extra set of eyes to work on the edits. I'm very interested in having a supported method to include OOT modules with Xilinx IP and extra non-top-level included files. Right now I've been applying this patch to all my local machines that need to build FPGA images.

**Comment by ejk43** [comment]
As a follow up to this PR, I now have an updated (and far more flexible) process to include OOT directories I wanted to share... 

1. Each OOT module has a Makefile.inc in the rfnoc directory (rfnoc-yourmodule/rfnoc/Makefile.inc)
2. This OOT Makefile.inc is free to call or include any other makefiles in the OOT repo. 
3. In the uhd-fpga repo, add an entry to the local makefile (in top/e300 or top/x300) that points to step 1's OOT makefile. Include the makefile for each OOT directory. 

I've just started working with this new process because I've found I need to include more varieties of IP in my OOT module than originally expected (xilinx generated IP, HLS IP, etc). This makefile process is nice because it avoids doing gymnastics in the uhd-fpga repo, it can still be very simple if there's just a few files, and it gives OOT module designers a good bit of flexibility to add other IP. 

Here's the two tricks that make this work:

1. Set up the OOT_DIR variable before calling the OOT Makefile.inc.
2. In the OOT Makefile.inc, redefine a new directory variable unique to this OOT module based on the OOT_DIR variable (example: `RFNOC_YOURMODULE_DIR := OOT_DIR`)

After that, the OOT makefiles can use RFNOC_YOURMODULE_DIR to point to the absolute path.  

Relevant files samples:
* Makefile in e300 repo: [Makefile.OOT.inc.txt](https://github.com/EttusResearch/fpga/files/869637/Makefile.OOT.inc.txt)
* Makefile in OOT repo: [Makefile.inc](https://github.com/EttusResearch/fpga/files/869635/Makefile.inc.txt)
* Makefile to include fpga-src in OOT repo: [Makefile.inc](https://github.com/EttusResearch/fpga/files/869632/Makefile.inc.txt)
 
Any thoughts? I'd be happy to move some of the corresponding edits in to uhd_image_builder and rfnocmodtool if it would help.

**Comment by ejk43** [comment]
Content in this PR is stale. I've updated for the more recent uhd-fpga in a different place. Closing PR.

**Pull request closed without merging**
